[package]
name = "nbodysim"
version = "2.0.0"
edition = "2021"

[dependencies]
winit = "0.26.1"
wgpu = "0.12.0"
cgmath = "0.18.0"
raw-window-handle = "0.4.2"
rand = "0.8.4"
rand_distr = "0.4.1"
ron = "0.7.0"
serde = "1.0.104"

[build-dependencies]
glsl-to-spirv = "0.1.7"
